library(data.table)
library(tidyverse)
library(glue)


                                                                                                                                                                                                                                                
outputDir<-"/u/flashscratch/j/jessegar/FilteringResequenceHighP"                                                                                                                                                                                                                                                          
SGETaskID<-parse_integer(Sys.getenv("SGE_TASK_ID"))                                                                                                                                                                                                                                                                       
msmc<-"/u/home/j/jessegar/project-klohmuel/msmc-master/msmc"                                                                                                                                                                                                                                                                                                                          
individuals<-c("BER.1.00F",                                                                                                                                                                                                                                                                                            
"CHE.100X.00F",                                                                                                                                                                                                                                                                                                        
"CHI.3b.00F",                                                                                                                                                                                                                                                                                                          
"CLO.4.00F",                                                                                                                                                                                                                                                                                                           
"CVD.8.00F",                                                                                                                                                                                                                                                                                                           
"FHL.5.00F",                                                                                                                                                                                                                                                                                                           
"GRV.2.00F",                                                                                                                                                                                                                                                                                                           
"GRV.7.00F",                                                                                                                                                                                                                                                                                                           
"HV.1.00F",                                                                                                                                                                                                                                                                                                            
"JAS.5.00F",                                                                                                                                                                                                                                                                                                           
"LAY.5.00F",                                                                                                                                                                                                                                                                                                           
"LAY.6.00F",                                                                                                                                                                                                                                                                                                           
"LYN.4.00F",                                                                                                                                                                                                                                                                                                           
"MAR.B.00F",                                                                                                                                                                                                                                                                                                           
"MCK.5.00F",                                                                                                                                                                                                                                                                                                           
"MOH.3.00F",                                                                                                                                                                                                                                                                                                           
"MTR.3.00F",                                                                                                                                                                                                                                                                                                           
"PEN.5.00F",                                                                                                                                                                                                                                                                                                           
"ROV.3.00F",                                                                                                                                                                                                                                                                                                           
"SUN.5.00F",                                                                                                                                                                                                                                                                                                           
"UKI.5.00F",                                                                                                                                                                                                                                                                                                           
"WLT.2.00F")                                                                                                                                                                                                                                                                                                           
filters<-tibble(                                                                                                                                                                                                                                                                                                          
  msmc=msmc,                                                                                                                                                                                                                                                                                                      
  individual=individuals,
  msmcIterations=200
)                                                                                                                                                                                                                                                                                                                         
filters<-filters %>% 
	mutate(msmcInput=glue("{outputDir}/{individual}.2018wgs3.ef.chr*_postMultiHetSep.txt")) %>%
	mutate(command=glue("{msmc} -t 12 -i {msmcIterations} -o {outputDir}/{individual} {msmcInput}"))

glue("Running: {filters$command[SGETaskID]}                                                                                                                                                                                                                                                                               
     ")                                                                                                                                                                                                                                                                                                                   
system(filters$command[SGETaskID])            
